sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t docker-react -f Dockerfile.dev .

script:
  # -- --coverage automatically exits when the test suit is done
  - docker run -e CI=true docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: "eu-west-1"
  app: "docker-react"
  env: "docker-react"
  bucket_name: "elasticbeanstalk-eu-west-1-826171241139"